name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'device codename (e.g mido)'
          required: true
      repo:
          description: 'Kernel source link (dont include . git at the end)'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true
      token:
          description: 'Telegram bot token'
          required: false
      chat_id:
          description: 'Telegram chat id'
          required: false


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "IM"
          git config --global user.email "IM1994@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update -y 
          sudo apt upgrade -y 
          sudo apt install nano bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python-is-python3 ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu -y  sudo apt install build-essential -y sudo apt install libssl-dev libffi-dev libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev libsqlite3-dev make gcc -y sudo apt install pigz -y sudo apt install python2 -y sudo apt install python3 -y sudo apt install cpio -y sudo apt install lld -y sudo apt install llvm -y sudo apt-get install g++-aarch64-linux-gnu -y sudo apt install libelf-dev -y sudo apt install neofetch -y neofetch

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "mido" ]; then
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/mido_build_script.sh
            bash mido_build_script.sh
          elif [ "${DEVICE}" = "santoni" ]; then
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/santoni_build_script.sh
            bash santoni_build_script.sh
          elif [ "${DEVICE}" = "j6primelte" ]; then 
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/j6primelte_build_script.sh
            bash topaz_build_script.sh
          elif [ "${DEVICE}" = "sweet" ]; then
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/sweet_build_script.sh
            bash sweet_build_script.sh
          else
            echo "Device not supported yet"
          fi


